/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservationsystem.Admin;

import busreservationsystem.Conn;
import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Smart pc
 */
public class AddEmployee extends javax.swing.JPanel {

    String Name,Email,Phone,User,Pass;
    /**
     * Creates new form AddEmployee
     */
    public AddEmployee() {
        initComponents();
        
    }
    CardLayout layout;
    JPanel parentCard;
    
    public AddEmployee(CardLayout card, JPanel parentCont ) {
        initComponents();
        this.layout = card;
        this.parentCard = parentCont;
        //parent = (JPanel) getParent();
        //layout = (CardLayout) parent.getLayout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textPass = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        textConfirmPass = new javax.swing.JPasswordField();
        btnAdd = new com.k33ptoo.components.KButton();

        jButton1.setText("jButton1");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel6.setText("Add New Employee");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservationsystem/assets/arrow_left.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Titillium Up", 0, 24)); // NOI18N
        jLabel8.setText("Login Credentials");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 30));
        jPanel2.add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 32));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("Email Address");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));
        jPanel2.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 310, 32));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setText("Phone Number");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        jPanel2.add(textPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 290, 32));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setText("Full Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel13.setFont(new java.awt.Font("Titillium Up", 0, 24)); // NOI18N
        jLabel13.setText("Personal Information");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel14.setText("Password");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));
        jPanel2.add(textUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 230, 32));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel15.setText("Username");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        textPass.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        textPass.setMinimumSize(new java.awt.Dimension(6, 20));
        textPass.setPreferredSize(new java.awt.Dimension(6, 20));
        jPanel2.add(textPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 210, 32));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel16.setText("Confirm Password");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        textConfirmPass.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel2.add(textConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 210, 32));

        btnAdd.setText("Add New Employee");
        btnAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        layout.show(parentCard,"Employee");
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Name = textName.getText();
        Email = textEmail.getText();
        Phone = textPhone.getText();
        User = textUsername.getText();
        Pass = textPass.getText();
        try {
                        Conn c = new Conn();
                        String str = "INSERT INTO employees (name,email,phone) values( '"+Name+"', '"+Email+"', '"+Phone+"')";
                        
                        c.s.executeUpdate(str);
                        c.c.close();
                        c = new Conn();
                        str = "INSERT INTO users (username,password,userid,role) values( '"+User+"', '"+Pass+"', (select id from employees where email = '"+Email+"'),'employee')";
                        
                        c.s.executeUpdate(str);
                        JOptionPane.showMessageDialog(null,"Employee Added");
                        setVisible(false);
                    
                    } catch (Exception e) {
                        e.printStackTrace();
        	    }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnAdd;
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField textConfirmPass;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textName;
    private javax.swing.JPasswordField textPass;
    private javax.swing.JTextField textPhone;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
