/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservationsystem.Admin;

import java.awt.CardLayout;
import javax.swing.*;
import busreservationsystem.AdminDashboard;
import busreservationsystem.Conn;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Smart pc
 */
public class Employee extends javax.swing.JPanel {

    private JPanel parentCard;
    AdminDashboard AD;
    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        //parent = (JPanel) getParent();
        //layout = (CardLayout) parent.getLayout();
        
    }
    
    CardLayout layout;
    JPanel panelCont;
    
    public Employee(CardLayout card, JPanel parentCont ) {
        initComponents();
        this.layout = card;
        this.panelCont = parentCont;
        DefaultTableModel model = new DefaultTableModel(new String[]{"Employee Name", "Email", "Joining Date", "Phone Number"}, 0);
        Conn c = new Conn();
        String sql="SELECT * FROM employees";
        try {
            ResultSet rs = c.s.executeQuery(sql);
            while(rs.next())
{
    String d = rs.getString("name");
    String e = rs.getString("email");
    String f = rs.getString("joining_date");
    String fs = rs.getString("phone");
    model.addRow(new Object[]{d, e, f,fs});
}
            jTable1.setModel(model);
            //parent = (JPanel) getParent();
            //layout = (CardLayout) parent.getLayout();
        } catch (SQLException ex) {
            Logger.getLogger(Employee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setText("Employees");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 37, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 730, 370));

        kButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        kButton2.setLabel("Add New Employee");
        kButton2.setRequestFocusEnabled(false);
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 240, 50));

        kButton3.setText("Update Employee");
        kButton3.setToolTipText("");
        kButton3.setEnabled(false);
        kButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        kButton3.setMaximumSize(new java.awt.Dimension(185, 29));
        kButton3.setMinimumSize(new java.awt.Dimension(185, 29));
        jPanel1.add(kButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 220, 50));

        kButton4.setText("Delete Employee");
        kButton4.setToolTipText("");
        kButton4.setEnabled(false);
        kButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPanel1.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        AD = new AdminDashboard();
        layout.show(panelCont,"AddEmployee");
    }//GEN-LAST:event_kButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    // End of variables declaration//GEN-END:variables
}
