/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservationsystem;

/**
 *
 * @author Smart pc
 */
public class MainAdmin extends javax.swing.JPanel {

    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textTotalEmp1 = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textTotalBus = new javax.swing.JLabel();
        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textTotalRou = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel4 = new com.k33ptoo.components.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        textTotalRes = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kGradientPanel5 = new com.k33ptoo.components.KGradientPanel();
        jLabel12 = new javax.swing.JLabel();
        textTotalResT = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textTripRoute = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textTripRoute1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 552));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setText("Welcome Back, Admin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 37, -1, -1));

        kGradientPanel1.setkEndColor(new java.awt.Color(98, 168, 67));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(22, 169, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservationsystem/assets/leadership_60px.png"))); // NOI18N
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Employees");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textTotalEmp1.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        textTotalEmp1.setForeground(new java.awt.Color(255, 255, 255));
        textTotalEmp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTotalEmp1.setText("999");
        kGradientPanel1.add(textTotalEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 133, 80));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 80, 212, 109));

        kGradientPanel2.setkEndColor(new java.awt.Color(98, 168, 67));
        kGradientPanel2.setkGradientFocus(200);
        kGradientPanel2.setkStartColor(new java.awt.Color(22, 169, 255));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservationsystem/assets/bus_60px.png"))); // NOI18N
        kGradientPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Buses");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textTotalBus.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        textTotalBus.setForeground(new java.awt.Color(255, 255, 255));
        textTotalBus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTotalBus.setText("999");
        kGradientPanel2.add(textTotalBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 133, 80));

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 80, 209, 109));

        kGradientPanel3.setkEndColor(new java.awt.Color(98, 168, 67));
        kGradientPanel3.setkGradientFocus(200);
        kGradientPanel3.setkStartColor(new java.awt.Color(22, 169, 255));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservationsystem/assets/waypoint_map_60px.png"))); // NOI18N
        kGradientPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Routes");
        kGradientPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textTotalRou.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        textTotalRou.setForeground(new java.awt.Color(255, 255, 255));
        textTotalRou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTotalRou.setText("999");
        kGradientPanel3.add(textTotalRou, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 133, 80));

        jPanel1.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 79, 211, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel8.setText("Waiting For Departure");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 357, -1, -1));

        kGradientPanel4.setkEndColor(new java.awt.Color(98, 168, 67));
        kGradientPanel4.setkGradientFocus(350);
        kGradientPanel4.setkStartColor(new java.awt.Color(22, 169, 255));
        kGradientPanel4.setMinimumSize(new java.awt.Dimension(304, 110));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Reservations So Far");
        kGradientPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textTotalRes.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        textTotalRes.setForeground(new java.awt.Color(255, 255, 255));
        textTotalRes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTotalRes.setText("999");
        kGradientPanel4.add(textTotalRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 80));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservationsystem/assets/ticket_48px.png"))); // NOI18N
        kGradientPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jPanel1.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 220, 330, -1));

        kGradientPanel5.setkEndColor(new java.awt.Color(98, 168, 67));
        kGradientPanel5.setkGradientFocus(350);
        kGradientPanel5.setkStartColor(new java.awt.Color(22, 169, 255));
        kGradientPanel5.setMinimumSize(new java.awt.Dimension(304, 110));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Reservations Made Today");
        kGradientPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        textTotalResT.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        textTotalResT.setForeground(new java.awt.Color(255, 255, 255));
        textTotalResT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textTotalResT.setText("999");
        kGradientPanel5.add(textTotalResT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 210, 80));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/busreservationsystem/assets/ticket_48px.png"))); // NOI18N
        kGradientPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jPanel1.add(kGradientPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 220, 340, -1));

        textTripRoute.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        textTripRoute.setText("From Destination to Source");
        textTripRoute.setToolTipText("");
        jPanel1.add(textTripRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 404, -1, -1));

        jLabel11.setFont(new java.awt.Font("Titillium Lt", 0, 14)); // NOI18N
        jLabel11.setText("88 Seats Remaing, Departure at 88:88");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 410, -1, -1));

        textTripRoute1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        textTripRoute1.setText("From Destination to Source");
        textTripRoute1.setToolTipText("");
        jPanel1.add(textTripRoute1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 431, -1, -1));

        jLabel14.setFont(new java.awt.Font("Titillium Lt", 0, 14)); // NOI18N
        jLabel14.setText("88 Seats Remaing, Departure at 88:88");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 437, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel5;
    private javax.swing.JLabel textTotalBus;
    private javax.swing.JLabel textTotalEmp1;
    private javax.swing.JLabel textTotalRes;
    private javax.swing.JLabel textTotalResT;
    private javax.swing.JLabel textTotalRou;
    private javax.swing.JLabel textTripRoute;
    private javax.swing.JLabel textTripRoute1;
    // End of variables declaration//GEN-END:variables
}
